In [2]:
import numpy as np

a = np.array([12.25,24.12,54.36,23.14])
print a

[ 12.25  24.12  54.36  23.14]


In [4]:
import numpy as np

a = np.array([[2,3,4],[5,6,7],[8,9,10]])
print a

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [9]:
import numpy as np

a = np.zeros((1,10))
a[0,5] = 11
print a

[[  0.   0.   0.   0.   0.  11.   0.   0.   0.   0.]]


In [10]:
import numpy as np

a = np.arange(12,38)
print a

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37]


In [18]:
import numpy as np

a = np.arange(12,38)
b = np.fliplr([a])[0]
print b

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13
 12]


In [34]:
import numpy as np

def isInner(i,j,n):
    if i == 0 or i == n - 1:
        return False
    elif j == 0 or j == n - 1:
        return False
    else:
        return True

a = np.ones([5,5])
for i in range(0,5):
    for j in range(0,5):
        if isInner(i,j,5):
            a[i , j] = 0
print a

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [41]:
import numpy as np

def printcheckboard(n):
    
    print("Checkerboard pattern:")
    x = np.zeros((n, n) , dtype=int)
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
    
    for i in range(n):
        for j in range(n):
            print str(x[i][j]) + " ",
        print 

printcheckboard(8)

Checkerboard pattern:
0  1  0  1  0  1  0  1 
1  0  1  0  1  0  1  0 
0  1  0  1  0  1  0  1 
1  0  1  0  1  0  1  0 
0  1  0  1  0  1  0  1 
1  0  1  0  1  0  1  0 
0  1  0  1  0  1  0  1 
1  0  1  0  1  0  1  0 


In [43]:
import numpy as np

a = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8])
print a

[1 2 3 4 5 6 7 8]


In [46]:
import numpy as np

a = ([8 , 4 , 6] , [1 , 2 , 3])
print np.asarray(a)

[[8 4 6]
 [1 2 3]]


In [55]:
import numpy as np

a = np.array([1 , 2 , 3 , 4 , 5 , 6])
print "Size of the array : " + str(a.size)
print "Total bytes used : " + str(a.nbytes)
print "Bytes per element : " + str(a.nbytes / a.size)

Size of the array : 6
Total bytes used : 48
Bytes per element : 8


In [56]:
import numpy as np

a = np.array([0 , 10 , 20 , 40 , 60 , 80])
b = np.array([10 , 30 , 40 , 50 , 70 , 90])
print np.setdiff1d(a , b)

[ 0 20 60 80]


In [57]:
import numpy as np

a = np.array([0 , 10 , 20 , 40 , 60 , 80])
b = np.array([10 , 30 , 40 , 50 , 70 , 90])
print np.setdiff1d(np.union1d(a , b) , np.intersect1d(a , b))

[ 0 20 30 50 60 70 80 90]


In [59]:
import numpy as np

a = np.array([0 , 10 , 20 , 40 , 60 , 80])
b = np.array([10 , 30 , 40 , 50 , 70 , 90])
print np.union1d(a , b)

[ 0 10 20 30 40 50 60 70 80 90]


In [69]:
import numpy as np

a = np.array([1 , 2 , 3 , 4])
print np.array(list(a) * 2)
print np.array(list(a) * 3)

[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


In [71]:
import numpy as np

a = np.array([1 , 2])
b = np.array([4 , 5])
print a > b
print a >= b
print a < b
print a <= b

[False False]
[False False]
[ True  True]
[ True  True]


In [74]:
import numpy as np

a = np.zeros([1,5])
print a
a1 = a.astype(int)
print a1

b = np.ones([1,5])
print b
b1 = b.astype(int)
print b1

[[ 0.  0.  0.  0.  0.]]
[[0 0 0 0 0]]
[[ 1.  1.  1.  1.  1.]]
[[1 1 1 1 1]]


In [75]:
# Q17 did not understand

In [78]:
import numpy as np

a = np.array([[10 , 20 , 30] , [20 , 40 , 50]])
a = a.flatten()
print a

[10 20 30 20 40 50]


In [84]:
import numpy as np

a = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
print a.shape
print a.dtype

(2, 3)
int64


In [85]:
import numpy as np

a = np.array([[1 ,2] , [3 , 4] , [5 , 6]])
print a.reshape([2,3])

[[1 2 3]
 [4 5 6]]


In [86]:
import numpy as np

a = np.array([[2 , 4 , 6] , [6 , 8 , 10]])
a = a.astype(float)
print a

[[  2.   4.   6.]
 [  6.   8.  10.]]


In [89]:
import numpy as np

a = np.full([3,5] , 2)
print a

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


In [93]:
import numpy as np

a = np.empty(4 , dtype=np.int64)
a.fill(10)
print a

[10 10 10 10]


In [96]:
import numpy as np

a = np.eye(3)
print a

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [98]:
import numpy as np

a = np.diagflat([4,5,6,8])
print a

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [2]:
import numpy as np

a = np.arange(0 , 50)
print a
b = np.arange(10 , 50)
print b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
import numpy as np

a = np.arange(2 , 10)
print a[3]

5


In [15]:
import numpy as np

x = np.array([[1,2,3]])
print x
x = np.swapaxes(x,0,1)
print x

[[1 2 3]]
[[1]
 [2]
 [3]]


In [17]:
import numpy as np

x = np.zeros((3, 4))
y = np.expand_dims(x, axis=1).shape
print x.shape
print y

(3, 4)
(3, 1, 4)


In [20]:
import numpy as np

a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array( [[0, 2, 4], [6, 8, 10]])
print np.concatenate((a, b), axis=1)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [25]:
import numpy as np

a = np.arange(1 , 14)
print a
print np.split(a , [2 , 6])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13])]


In [1]:
import numpy as np

x = np.arange(16).reshape((4, 4))
print x
print np.hsplit(x, [2, 6])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


In [2]:
import numpy as np

x = np.zeros((5,5))
print x
x += np.arange(5)
print x

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [4]:
import numpy as np

Z = np.linspace(0,1,11,endpoint=False)[1:]
print Z

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [5]:
import numpy as np

x = np.arange(0, 1000)
print x

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [6]:
import numpy as np

x = np.arange(0, 100)
index = [0 , 3 , 4]
x = np.delete(x , index)
print x

[ 1  2  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77
 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [10]:
import numpy as np

x = np.arange(-15 , 50)
print x
x[x < 0] = 0
print x

[-15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2
   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  2  3  4  5  6  7  8  9
 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
import numpy as np

x = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])
print x
print x[~np.isnan(x).any(axis=1)]

[[  1.   2.   3.]
 [  4.   5.  nan]
 [  7.   8.   9.]
 [  1.   0.   1.]]
[[ 1.  2.  3.]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]


In [11]:
import numpy as np

a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
print a
print b
print b[(100 < a) & (a < 110)]

[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
['e' 'i']


In [12]:
import numpy as np

x = np.array([2, 3])
y = np.array([])
print x.size
print y.size

2
0


In [13]:
import numpy as np

x = np.array([[20,20,20],[30,30,30],[40,40,40]])
print x
v = np.array([20,30,40])
print v
print x / v[:,None]

[[20 20 20]
 [30 30 30]
 [40 40 40]]
[20 30 40]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
import numpy as np

print"Add: ",
print np.add(1.0, 4.0)
print "Subtract: ",
print np.subtract(1.0, 4.0)
print "Multiply: ",
print np.multiply(1.0, 4.0)
print "Divide: ",
print np.divide(1.0, 4.0)

Add:  5.0
Subtract:  -3.0
Multiply:  4.0
Divide:  0.25


In [20]:
import numpy as np

x = np.arange(0 , 15)
print x 
print np.remainder(x, 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2]


In [22]:
import numpy as np

x = np.round([1.45353, 1.502421, 1.123255])
print x
x = np.round([0.34328, 0.33550, 0.231464], decimals=1)
print x
x = np.round([.123215, 1.5, 2.5, 3.5, 4.5])
print x

[ 1.  2.  1.]
[ 0.3  0.3  0.2]
[ 0.  2.  2.  4.  4.]


In [23]:
import numpy as np

x = np.random.random((5,3))
print x
y = np.random.random((3,2))
print y
z = np.dot(x, y)
print z

[[ 0.9853995   0.61792532  0.98616202]
 [ 0.13107089  0.87654601  0.97679673]
 [ 0.24253356  0.45044698  0.58112401]
 [ 0.20601516  0.16334432  0.00481935]
 [ 0.38082822  0.93581773  0.39177372]]
[[ 0.27959943  0.24250461]
 [ 0.20285332  0.83963521]
 [ 0.15511333  0.9544535 ]]
[[ 0.55383222  1.69904157]
 [ 0.36597181  1.70007124]
 [ 0.24932699  0.99168249]
 [ 0.09148421  0.19170912]
 [ 0.35708241  1.25202791]]


In [24]:
import numpy as np

x = np.arange(24).reshape((2,3,4))
print("Array x:")
print(x)
print("Array y:")
y = np.arange(4)
print(y)
print("Inner of x and y arrays:")
print(np.inner(x, y))

Array x:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array y:
[0 1 2 3]
Inner of x and y arrays:
[[ 14  38  62]
 [ 86 110 134]]


In [25]:
import numpy as np

x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print x
print y
print(np.inner(x, y))
print(np.outer(x, y))
print(np.cross(x, y))

[ 1.  4.  0.]
[ 2.  2.  1.]
10.0
[[ 2.  2.  1.]
 [ 8.  8.  4.]
 [ 0.  0.  0.]]
[ 4. -1. -6.]


In [26]:
import numpy as np
x = [[1, 5], [3, 1]]
y = [[6, 1], [2, 4]]
print(x)
print(y)
print(np.matmul(x, y))

[[1, 5], [3, 1]]
[[6, 1], [2, 4]]
[[16 21]
 [20  7]]


In [27]:
import numpy as np

x = np.array([[10, 30], [20, 60]])
print(x)
print(x.mean(axis=0))
print(x.mean(axis=1))

[[10 30]
 [20 60]]
[ 15.  45.]
[ 20.  40.]


In [28]:
import numpy as np

x = np.random.randn(1000)
print "Average : ",
print x.mean()
print "Standard deviation : ",
print x.std()
print "Variance : ",
print x.var()

Average :  0.03604286066
Standard deviation :  0.987269317385
Variance :  0.97470070505


In [1]:
import csv
import numpy

filename = 'pima-indians-diabetes.data.csv'
raw_data = open(filename, 'rt')
reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
x = list(reader)
data = numpy.array(x).astype('float')
print(data.shape)

(768, 9)


In [2]:
import numpy

filename = 'pima-indians-diabetes.data.csv'
raw_data = open(filename, 'rt')
data = numpy.loadtxt(raw_data, delimiter=",")
print(data.shape)

(768, 9)
